apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp-secrets
    namespace: prometheus
stringData:
    smtp_username: ENC[AES256_GCM,data:ALIwTiTdZsb+LDDgfSHpoOOgW5U=,iv:3HVN7mg+c5xYUrsjmidVedkJIU9raWZ/t63RXC/Wmik=,tag:rN733hSXv7FniVqIfv4eag==,type:str]
    smtp_password: ENC[AES256_GCM,data:Y+0fDyVkE8nIoTDF4TRA8A==,iv:K/UHpHLv/6rai51cFzxlhvl3hUSFzElrR5My/KUqivQ=,tag:0QbTiONgvJR9ChJUpO0tEA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1nrj26va2pfctt5znahwr6hq5vpftzp59dmh9cxdrp7hzgt2kfdgs6fzhzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibUpUcjBuN2FKa2NURjRS
            dE93R1NhVUZhR0UrS2hORHhnZXNmYjJoNFZvCmhaWEhxRjBIV1FUUDI5QTVWL0Zk
            Yi9SQ0w3V0drQVlzbmptL0FxbVR0SmcKLS0tIFNGeTVMQ1BGRGhMdzVBZnl2REFK
            U3RLV3p2OWUyTUl6VHBBd3psQ0RLNEEKHssssbZMDOQWBttVpAOkIkq+luKqI8uz
            /2o3Jc0borxGbkibHd3J1TfhIahChCTee39WXs+N26g9zvXKSo9SDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T03:29:36Z"
    mac: ENC[AES256_GCM,data:Ely06a+7FnSSbY2IPtS0g3wFE0a4daarnu0Uca6DC5qLKeCFJtv3Hgv/hW9UApH02g3RfbLLj6r1CURGbmXmNg/DXSm2XD2XE/0EYd4oCemVugN/Wxqytxt+E77Eaz63Z0r7dmHhdUTZU2V6QYvHUtaYiQtcvX2A6LSem0dMLvQ=,iv:inprADHAL8xO9Mpc4b78JI6j4D0UcjiUa6vL5DtZLI8=,tag:IjCD8X3QmjeF8Sz7AtxEBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
