apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: prometheus
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:+YpLi9lQ+w8MLGa+POtH9B3bn/wbAZqKDZlmbja71INjuxdmzocj2M1x3eVe78/69KEKGx1pAZcydWOS0npE4DNuFoWQlf5wHptLKOM3CIlBoEH5o9xbUBj11OIf3AoU9YMBK6bJtxheyWCFXIRP2IMLtu7wLt9Wk1rkr3qX5GjeKPORVBa2S4Qbeb/1dMKSjMbEuhTFQwlVTsa5YFAHA7YtmBtFJ3n+88u3utXUkcSMP2MGoIPE0EK95d/sh/HJ+TcqGs2/FA/3P+kgQzhd2qZOtOOvXU9CB92xr/ju9VY3UVT333mlp1eJPggRvEcakqMgI730AsYc/DhcF/7XOgX7VAsPix3wDYFbNTDp5qk0VokuW5nFMxFnqYA9zl9YYgk9bzvNMvGMT+1QFmyQ9B26x/T+VUI4zYn0v5pn5twZvdrr+7SOnPqrJI5fgzNjSTHAQYKsEfPP8mg36TYXBLEs0tB+biYlK9Kg7B02Z6eKVPXoDohmPBRIIUk0BSCyLI/SQBFPzxTBfM7bEpmanMkr4ka0NfR3gsf6ogijM0aR71JVV1W+3YFOXzrcEoAsgzAMdvxKGkgDI47zrDhJ2w==,iv:Xdj8VBmlxyBsayECyNyrg5B1myZv2h7tgFdJlp11dgU=,tag:QXiid9WzylPgYCW1m+zEMw==,type:str]
sops:
    age:
        - recipient: age1nrj26va2pfctt5znahwr6hq5vpftzp59dmh9cxdrp7hzgt2kfdgs6fzhzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aDZFWDVXaVJwZkltV1l0
            Z1FZb3o1dHdwRE1MQWMrU1Rvbm52R3YzQlZjCm9HV1MwU214UHMrMjNmTk9VZVZ3
            S1hjejZpUkw5RHRkT0JnMWdnZFZyM2cKLS0tIHM5MGRVNkNRMmxOU2d1cnEzSlov
            MC82Sy85aUg0WjNXUk1kTm4vQVRNNUkKTZmcBqkoNpsXsoAvc4bJ861v/8+bOIM0
            x2xRYcLJeDsK/WqVkeFO4zucx2RPxAf9Hm24kxQ8pmw1pyW2PV5Txg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T04:47:54Z"
    mac: ENC[AES256_GCM,data:Gsal//P8Hwe0xo8yO7XVGildABeXnfvAPLY+h/L8hlSp7FQY0Ow9Pcru/65ZNArDRmtvaq3amGP1YUJIbdl8eSNZ5/Si8hENH6upJY/qRg3Fiyy/TMA983zdApbRUsiQktnFMWWbvWKTkjG+WIah1KBGejUOvbc9Vxkt0VkGzb0=,iv:OcZ9GTrGTKRtLlMKEQkWbqKdFnQjsxH54kFyKf1r24I=,tag:XIeSU8BuaoMFESFxoqPALg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
