apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: prometheus
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:Eg220kHUd8t4CnRENFGElsjldDNRbwttVhKCfzvaWdta0MYRBIqzypiKmV1VezUbInLx+dQE9RfwmerFa0rl8iTsYIFJNGvQlyj6bGOJDzjrdqRmITVb9snDj39qFrxOCxysCyeTnb5ToOFVE84p1bOxrtnRxMFYOcO+oRjpgcZx2Fc2tfBPtU7cdJk198fHueRRB0Ej33fPfcxtTCpqcaCWit9Rlh4KekM8L68HarPXADTLdSzVIzDZYqtS6OqIjQYrve45K04Z1T6divK7oBzyFlIqUkdRCNP7XZ2YQMoAd5gE7vzFeS31zYMn4not9yljC3PTstdN9p2OL8aKj+VSaTE2sc9mqi021rmkeKkWYsYUpTfDKGf01QQboQB7BE3JAVDsMrcQKkTBvnZoievl0dpOUx3QVzqLKpwsHqCLhywbO1ccBhxVFHl9s3OJ1aOiKP7S7TOeSZlXQLii2iYi8pnhwGs8f1gGNVpy2j8YCtaOFvLfdpXaRxwU+FEZjl8cMnVwQUvPZh7js9qjdg6wTHmliSQtMoBVtLBiCCYIu3UB09M7nj6bAGekBrJlVwRoMJIxLCiRIlVK7tURO7BFAv5a9ZmwcoyCKhHhDDryyK8ai1UndmezqJ0gMstq/uc7hC03OGF8cafHvVg3IVDE6sXOSt2vzfSTrydo/O3/Fwayag==,iv:IXv6zJHeS6cWIW+kxyxQcanYakj4wivSDl6j1/zha8Y=,tag:Y40ov7JcPPO/OLVB5aQ/QQ==,type:str]
sops:
    age:
        - recipient: age1nrj26va2pfctt5znahwr6hq5vpftzp59dmh9cxdrp7hzgt2kfdgs6fzhzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RkdsZUZ3czZrT3lEYVFm
            Kzd5dmZUTldXRFhxTEcwdDlWd3AvcCtZMVY4Ck5kTHVQU3ZYR3p0VDFVZ0V5MGZa
            eHh4VEZWblB6ZGpRMTNyMC90K09URTAKLS0tIDhCWEVzSjZTTUNNV2xNQ2ZOYzEz
            blF1RVF1dGtkV0JFOER2MHJZUm51eGcKhmfwgRf/gPqqH9R6UiPPx5C4KKqh9YES
            I/+HqHszKR5BOQsnpl7Yj4wgjiRFEyXXrMxZRwxBwywHgBGXA8DO1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T05:13:47Z"
    mac: ENC[AES256_GCM,data:oQ3qzdC7PSgFGbIJwJiouBh84WEkdpUENjsU3lZcx3WMwyPKdiMKmFtU/GZkA9N05L5rE7LGX4Er1o/o/igOrk8/itqmwQAgW/wrDvpIG9mpcwFJR1IN7wccWGJFmVl0pPR3bZHbIlcKEo9gZIT4AeFwUQX/TYLCTDlFQ5hrb28=,iv:7PFkLGR6GDEi8ZjPCVOD6UaW0M+EKcmAlh3LoxeSc/w=,tag:uqff5fJFMkKQt4B4inWhtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
