apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: prometheus
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:m0He4uIUbmru9/Q3imM5jrVkQqVWz6uUSvOSJPOd4nDHNopXke2W8KN7VenvgvvmMNCfGC0M0MlSkSC/yPMTa7Y+alhjiddk5syNFtkJqX7R8CWmPpAzLKQSmWeqG6SJrm/aVrEJ6a4BojQTKAtjL7o6EakLg9V6DRRrkiJ12zAyHpHiRukYfSyerAbOGvXKfq8x/BxpXWhI6CCJrqpzKmE+bKgy1Zl+kXhaClqYLkCuWrWm9QyOYGf/0Y8aLq5neN1IqyeXxZCcMZ+id1H7mFCuXoDkYEvBtXzG8Uu72S8DBOhiIgjm/7tpL/CQNvfKjHxdQvhAejoVH5FshJUP1XKknbczUzlZ+AWkZcgAHLoJbUNMTWWqLeMihgQnrWDkP6fJHvYOB+CJCWdTt19AY34XG6zor1AUG5AUwI8Re4wk8QudjCqxkPXRSuuBM0EKaskr27bIsTjWkOhyq1lGMFxL6dXz5dDnYF6Nk1gt5Ko9nzG4j8AbvGx5KGb9HCjslYxgcvyVgA4fsXpna9BlCtC0DYyjDyHpv7IjZh1RBKMAAyBpuBvqsh0KLJGNoAefF1f9Rhl6q1QeGBOHj9HhgoWIz1rP0KSxdKTW1o5YuEWyL5wxS3zMQNGhg0xM7fVrw68ySXHl295PyT8qoXQBqc9qytuZxprLWb1RYr3dughZHD8tiqP+q9jlctbQy4zfWoKQz2e3BuGOUEcjl/zxFBpTVUJ7k0cLlEqfgbtpa61UqPPyD5N5WRb8clxkDVnFeafdfNsZe03Y3ZATpRIa+8yvudgPV88gVj7Vty45x3ExHYKV0xxS+XNk2czT7erxJ18bRcACMlaJkzQKGbsXa/MWSEUWCSdHIkiBgFvacfGEIR9/yIIzO5cwAKZPwjBvDjJQpwG0oeI0FDvE/Kseu+UxdKRCgrxMyA==,iv:xkiCId4F8TDgyaksOJqHyxjDgwJ9c8glo0spEdIBvtQ=,tag:xCNI/creeTreuiI2wbHy2g==,type:str]
sops:
    age:
        - recipient: age1nrj26va2pfctt5znahwr6hq5vpftzp59dmh9cxdrp7hzgt2kfdgs6fzhzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RllhenBwVk11MWh5akpz
            d0wxYTVoS1NMUjEyNFQ5NGpLOSszeml3b2lnCklBTGtRZEhrOG1tK2lucVFkWi9J
            VVArb1lRdmlSMkxMWnBkTEtuY1JRRVUKLS0tIHJJbE8yWUpUTzRtc0cwWDJvS3JD
            ZTc3TE5qVGJMUkRrUm95RW5LQ1AraDgKhuKxwaO73MlgCOBujt1gqgyDJr20ZK1W
            Zelxq5MAs25z1Nve5kSOz8ORQMhEY5y4Gs5Dfq40oDpySUMGZWwYHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T02:41:34Z"
    mac: ENC[AES256_GCM,data:SyTKBuyyyrj1P5LSyRSLoIst5pM4gTLVWm7YnDRqTKMhhKtHICOwy9afQbGBYw4zQa/NHfI0Q48H7Ct1ASD3Cksw4DfZRTdc0KFjYOQYV6TQEmKxh+sr86W2Kyxslejt/ORpeS/cxJX22Gxhl2VxKVO+LN8hLWtlGIY42opC0ZA=,iv:W2dYCRt8AQmkA7UIuiOOypP+plfvpvCDqjV072KoM3I=,tag:LxBRABr6I6K+6OWb6U/tqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
