apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: prometheus
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:jQTsJ8xXYyGtREjI1kGJDvZE0e/mnG3+vKXqtz5nTKfa8VHiQC1yFhh5MU5rprYn1PH7gFFv7YXs3xv/4XQu6XZU8Un4mUGY1eBGudBXhd9GyNu3rm3aGtEl4w0MYP7of8PGin1Jd17Ao1LBVm1fhqjSECVkIwsNWF4zkCUTudgkX5to34Egh1kKmVbzXfC0mY8pESZXbvv+yMtOCKmZ9+3HH89yh8G7w///xaoCtRpyqbVsxJ0GjPKmPFODdiWYIXTVr7NgME2THdEFNO5MDI7+xeq5MlvEesOlFUHau9DSB7carXJGYBI8oU7R71WpvXDzKYqDsCeUMRkk0A37gFVo/FV6wSSexrIFcQL1vTBVWnNN5mF6UzsqWaWROzpnX97NWPlSk0qV141+4v15xWK4bwjB13psd8/6gzk9QdROhrLvNt3TSzhihTa9vMQvmdSAnbQnuzC0bQZSQR4GVdA26NqlGGzVizdyJYgdOzDS8AcUwjtGue+T0DDmWEp/NwrdhFD5fGqSY/2PKl7znHZH6IBGrIZsIc4cmpTZvSqRtr1miaK5bYQwDTisW6Nbu55OazYoBiukB0GiYVb65RnCzQ6dvTo2xuk5herKKEarSSk3ZaDPbQnjmH2LQf4eadwdVzkKGp1Ih5fwQ39x/CkdCDm/KjTeYyMKegXKol6+mNXFkNVEUcVORnCGm4nVLAbDPFSn7omvujPKeM+biF9lRHTPNjGS6kr4Kyb4rbn4U5pJQV7b9dqugw8Iz2y7GRXO7xz4f6HGgHiEAtrCTf9fUz6uwtsbwZze5OHrpsuOFiRSSGGLIQclrnDS9M/gz3bbMCmVxfzbgnI+xn0iCP8TGWyELZs1yon6CqZvYbMZ8wXEXluRjH00NC3PFp+T5Ata//zqWMj9suBmT8XJey9sfQHsFaqfWRRsiitcBcg/UUImvSwku43niOE//FqK5/rcNcqfzIKfAuaYkL+iWCESfc1DW7OXBD+PpdFtQKVlYMZa2vRUG2U6ueAnCmzQyfDPr2/qZCTxS+PkAlXSFM9N9KYGiKyR72PTw/HzRd18dN5EKtMlElDamgXsgmlr86Pw6R8Irfu2,iv:5iock1MCdHOOdNqo2jy8qG9zpghpknaV/o1POJxeBRE=,tag:mF9/rQeSQDqLR0zw5lc6BQ==,type:str]
sops:
    age:
        - recipient: age1nrj26va2pfctt5znahwr6hq5vpftzp59dmh9cxdrp7hzgt2kfdgs6fzhzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TWg5NlFKR0hRNW1MeFhv
            RTBZMmJTVmRZTEhkRzMwWHJHaG5pWU41U0NVClhKc1ZTNlR2cTgxdHZHSFpGdU9F
            eVJ5K2ExUUt0R1MzNng0L0V3OHVBbkkKLS0tIHlFS0ZoclRpaGpXTTI1WFZRNFpk
            eE5wRHlxRFFpVEkxM1UwdVB2dGZtaVEKBBR7CXIfZByERCuQ+0tMd3naS4c9ThZV
            xPriKMlzV9SGxnVAyHXc4OlzVyikRTBTJg3Jt/BZBk929FgQwCLwKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T08:24:03Z"
    mac: ENC[AES256_GCM,data:3xe4MAnOb2Nu5wlJBDJ44DzQMC9+Lmrz9c6a1n+jq63a7wmdOnaFtKtTZ3edVSCoN2lmIJsQxzDs3mbl1QF6hHTB5e/eX+A9gysA74CEQlsDeD3dr75u/aZ4yJHrWHHZ0SNqw9SOHpTHxxuPsxk5MCezpjiCdeJL0OofDM/PxMs=,iv:axQfSg/a5UkzQkT6BsUOg2/QiohTQMecfMoWhlUGWsY=,tag:WTd+gnpEtcWQOWXvE95jCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
